# Generated by Django 5.2.6 on 2025-11-15 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Wolf', 'Wolf'), ('Pfadi', 'Pfadi'), ('Fenner', 'Fenner'), ('Wolf-Leiter', 'Wolf-Leiter'), ('Pfadi-Leiter', 'Pfadi-Leiter')], max_length=20)),
                ('second_level', models.CharField(blank=True, choices=[('Jung-Pfadi', 'Jung-Pfadi'), ('Pfadi', 'Pfadi'), ('OP', 'OP')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('pfadi_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='profiles.level')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
