# Generated by Django 5.2 on 2025-11-26 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Artikelnummer')),
                ('unit', models.CharField(blank=True, default='Stück', max_length=50, null=True, verbose_name='Einheit')),
                ('quantity', models.IntegerField(default=1, verbose_name='Menge')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Groesse')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Menge')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ausleihdatum')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('status', models.CharField(choices=[('borrowed', 'Ausgeliehen'), ('returned', 'Zurückgegeben')], default='borrowed', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Benutzer-E-Mail')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Anfrage-Datum')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert'), ('sold', 'Verkauft')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Benutzer-E-Mail')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verkauft am')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Menge')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='lager.item', verbose_name='Artikel')),
            ],
        ),
    ]
