# Generated by Django 5.2.6 on 2025-10-20 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('size', models.CharField(blank=True, help_text='Optional: Größenangabe für Artikel wie T-Shirts oder Schuhe', max_length=50, null=True, verbose_name='Größe')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Artikelnummer')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lager.category', verbose_name='Kategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Menge')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ausleihdatum')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Rückgabedatum')),
                ('status', models.CharField(choices=[('borrowed', 'Ausgeliehen'), ('returned', 'Zurückgegeben')], default='borrowed', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Menge')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='lager.item', verbose_name='Artikel')),
            ],
        ),
    ]
