# Generated by Django 5.2.6 on 2025-10-20 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Benutzer-E-Mail')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Anfrage-Datum')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Benutzer-E-Mail')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verkauft am')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Bemerkungen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lager.item', verbose_name='Artikel')),
            ],
        ),
    ]
