# Generated by Django 5.2.6 on 2025-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert'), ('sold', 'Verkauft')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
